### ISSUE TITLE
i can't pull image after update to core-2021.6.x

### ISSUE THREAD

**Issue by boyphongsakorn** [hassio-addons/addon-portainer#104]
I can't pull my self image or pull from App templates after update to core-2021.6.x

after create MySQL App templates, I got this error

`no such image: MySQL: lasted`

in Supervisor Log

`21-06-04 15:35:43 ERROR (MainThread) [aiohttp.server] Error handling request`

i don't know docker.io server is down or problem is my DNS

**Comment by frenck** [comment]
`lasted` is a typo...
