### ISSUE TITLE
Version is stale and old

### ISSUE THREAD

**Issue by unlucio** [hassio-addons/addon-portainer#106]
# Problem/Motivation

this addon installs a very old and stale version of this SW: 1.24 while we're on 2.5.1

## Expected behavior

when I install and addon I expect it to have one of the latest versions of the SW, not a super old one.

## Actual behavior

it installs a very old version of portainer

## Steps to reproduce

Install it and verify the installed portainer is screaming at you begging to be updated.

## Proposed changes
I tried to fix it my self opening a PR but it wasn't well accepted: https://github.com/hassio-addons/addon-portainer/pull/105

perhaps someone in the inner circle can open a more successful PR

**Comment by frenck** [comment]
That is not a bug, bug a feature request. The 1.x is still maintained btw and the 2.x branch will never make it into this add-on. If that is needed, the add-on would be deprecated and removed (and not upgraded).

**Comment by unlucio** [comment]
> the 2.x branch will never make it into this add-on. If that is needed, the add-on would be deprecated and removed (and not upgraded).
Wwhy so if I might ask? Sounds backward to me: if I have an addon I expect it to be updated, not to be deprecated and I've to manually take care of updating it. I can't really find the reasoning behind it 🤔

**Comment by frenck** [comment]
Authentication is no longer compatible. They commercialized the authentication part and the worse part is: they lie about it. Which is fine, but I won't support that.

**Comment by unlucio** [comment]
I'll admit I don't really follow the "soap operas" behind the different projects,
tho I've been running the 2.x for months and I haven't noticed any difference in the authentication.
My "update path" since 1.x (and in general with dockerized SW) is simply: pul the latest image and launch a new container from it, and it always worked like a charm with portainer too.
I guess it might make a difference in an "enterprise setup", but for personal use, I fail to see all the concern about this update.
