### ISSUE TITLE
Volume Mapping Bind

### ISSUE THREAD

**Issue by RobLoach** [hassio-addons/addon-portainer#11]
# Problem/Motivation

Can't `bind` volumes up to the host. When creating a Volume for a container, you can usually Bind the volumes so that the data is mounted in the host. Whenever you do this through Hassio, you get "read-only filesystem".

## Expected behavior

Be able to mount /share/myfolder from within a container.

## Actual behavior

You get "read-only filesystem"

## Steps to reproduce

![screenshot at 2019-01-18 02-12-32](https://user-images.githubusercontent.com/25086/51370892-965c7800-1ac6-11e9-80e7-31556a4360de.png)

## Proposed changes

Allow passing a mount directory to the Hassio Portainer config that will be mounted to the Portainer container.

**Comment by pergolafabio** [comment]
i have the same exact question
also a read-only error
so how to map to /config or /share ?
see my screen example here : https://www.dropbox.com/s/xiylzqs8d9v3vs3/errorhost.JPG?dl=0

**Comment by pergolafabio** [comment]
ok, found it 
/config is for example NOT /config
but : /mnt/data/supervisor/homeassistant

or /share is like : /mnt/data/supervisor/share
