### ISSUE TITLE
Primary menu is not showing

### ISSUE THREAD

**Issue by msl2000** [hassio-addons/addon-portainer#110]
# Problem/Motivation

I can't see the Primary menu list in the Portainer add on. I am trying to add a new container and I can
![image](https://user-images.githubusercontent.com/18165861/123352209-2eb58b80-d5a2-11eb-8a17-3fc8e3ddfc85.png)

## Expected behavior

See the Primary menu list so i can add a container

## Actual behavior

Primary menu list is not visible so I can't add a container

## Steps to reproduce

I simply installed the add on as expected: Install > disable protection mode > start

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by msl2000** [comment]
Please close this. Not an issue. I am just blind, thanks

**Comment by sinclairpaul** [comment]
You can close it by clicking the Close Issue Button 😉
![image](https://user-images.githubusercontent.com/24625998/123353777-47855900-d530-11eb-82c7-a803c8799ddd.png)
