### ISSUE TITLE
Update portainer to latest release

### ISSUE THREAD

**Issue by jmartens** [hassio-addons/addon-portainer#111]
# Problem/Motivation

> Update notification for Portainer CE, that a new release (2.6.0) is available

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

Can you please update the app to have latest portainer release?

**Comment by frenck** [comment]
See all other previous issues on the subject.
