### ISSUE TITLE
Portainer is not able to download extensions manifest on clean HassOS install

### ISSUE THREAD

**Issue by joaomlneto** [hassio-addons/addon-portainer#115]
# Problem/Motivation

Portainer is not able to download extensions from internet on a clean installation of Home Assistant.

This seems to be quite similar to #33 except I'm doing this on a clean install, not a snapshot recovery.

The link to the solution/workaround is broken (unixblogger.com domain now redirects to startpage.com), and since it's not documented anywhere else (**should have been included on the documentation for this addon!**)

## Steps to reproduce

1. Install Home Assistant OS 5.13 (RPi 4/400) using Raspberry Pi Imager
2. Perform initial setup
3. Setup Raspberry Pi 4 using WiFi rather than ethernet
    1. Set user to advanced mode
    2. Install "SSH & Web Terminal Addon"
    3. Disable protection mode in the addon
    4. Configure addon with a random password (`ssh.password` parameter)
    5. Run command: `nmcli device wifi connect "YOUR_SSID" password "YOUR_WIFI_PASSWORD"`
4. Install and configure Portainer
    1. Disable protection mode
    2. Navigate to Extensions page
    3. Witness the error `Portainer must be connected to the Internet to fetch the list of available extensions.`

The problem persists if, after those steps, I connect the Raspberry Pi via ethernet. So, Wifi may not be the problem, as in #33 .

**Comment by frenck** [comment]
The add-on does not provide connection to the internet, that is not an add-on responsibility or concern. Please report your issue with the upstream project.

**Comment by joaomlneto** [comment]
@frenck Would the upstream project be https://github.com/home-assistant/operating-system ?
