### ISSUE TITLE
2.6.1 install(update) error

### ISSUE THREAD

**Issue by GHSTUDIO1** [hassio-addons/addon-portainer#116]
The command '/bin/bash -o pipefail -c apk add --no-cache nginx && if [ "${BUILD_ARCH}" = "aarch64" ]; then ARCH="arm64"; fi && if [ "${BUILD_ARCH}" = "armhf" ]; then ARCH="arm"; fi && if [ "${BUILD_ARCH}" = "armv7" ]; then ARCH="arm"; fi && if [ "${BUILD_ARCH}" = "amd64" ]; then ARCH="amd64"; fi && curl -L -s "https://github.com/portainer/portainer/releases/download/${BUILD_UPSTREAM}/portainer-${BUILD_UPSTREAM}-linux-${ARCH}.tar.gz" | tar zxvf - -C /opt/' returned a non-zero code: 1# Problem/Motivation

Running HA under Debian 10.

**Comment by sinclairpaul** [comment]
Maybe you could add some context on what you are trying to do, it would appear you are trying to build the addon, which isn't necessary, as the container is distributed.

**Comment by GHSTUDIO1** [comment]
I just saw an update available and did the update.  When that didn't work (message above), I uninstalled the addon, reinstalled it and got the same message.

**Comment by sinclairpaul** [comment]
Please post the full startup log

**Comment by sinclairpaul** [comment]
I'll actually close this out, looks like you have installed an addon from another repo, I am guessing this https://github.com/alexbelgium/hassio-addons/tree/master/portainer

Please report your issue there.
