### ISSUE TITLE
Failed loading Endpoint, Unable to connect to the  docker endpoint

### ISSUE THREAD

**Issue by f3bandit** [hassio-addons/addon-portainer#132]
# Problem/Motivation
Failed loading Endpoint, Unable to connect to the  docker endpoint

## Expected behavior
to work properly and show containbers, images, etc

## Actual behavior
error messege and no joy

## Steps to reproduce
I did this on a clean install of latest HA from USB SSD as well as from latest HA from MicroSD, nothing else installed.
HA first bott setup and installed portainer from the supervisor add-on store

## Proposed changes
Honestly no idea!?! short of pulling out the youngling slayer 9000 and hoping for the best.
> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by nomis52** [comment]
I've seen the same issue. If I use the version prior to #126 it works correct. 

```
# ha info
arch: aarch64
channel: stable
docker: 20.10.7
features:
- reboot
- shutdown
- services
- network
- hostname
- timedate
- agent
- haos
hassos: "6.3"
homeassistant: 2021.9.6
hostname: homeassistant
logging: info
machine: raspberrypi4-64
operating_system: Home Assistant OS 6.3
state: running
supervisor: 2021.09.0
supported: true
supported_arch:
- aarch64
- armv7
- armhf
```

Oddly enough once I removed the old version and tried 2.6.2 again it worked !
