### ISSUE TITLE
Portainer Edge Agent Port 9000

### ISSUE THREAD

**Issue by Salvora** [hassio-addons/addon-portainer#141]
# Problem/Motivation

I've tried to deploy and connect a remote edge agent to this addon but apparently you need port 9000 open for this to work.
This has been suggested before in https://github.com/hassio-addons/addon-portainer/issues/44 but it has been a while and since with the update to the new Portainer CE, it is required to enter the username and password for login, is it possible to open the port 9000 like another addons?

## Expected behavior

The ability to specify the port for Web Interface.

## Actual behavior

Only port 8000 is available

## Proposed changes

Adding an option to open port 9000.

**Comment by Salvora** [comment]
Well, with the new portainer 2.9.0, there is now port 9443 for https. I am not sure if it is needed for the edge client though.

**Comment by Salvora** [comment]
bump

**Comment by frenck** [comment]
This add-on is being discontinued.
