### ISSUE TITLE
default password for portaijer addon

### ISSUE THREAD

**Issue by yousaf465** [hassio-addons/addon-portainer#147]
what isvthe default password for portainer add-on. login was introduced in recent version. I cant remember setting up the login information for protainer. how do I retrieve my login info?

**Comment by chaosye0** [comment]
same issue

**Comment by yousaf465** [comment]
> same issue

Instead of official add-on use https://github.com/MaxWinterstein/homeassistant-addons

**Comment by frenck** [comment]
This add-on is being discontinued.
