### ISSUE TITLE
Duplicate of #4

### ISSUE THREAD

**Issue by dogmatic69** [hassio-addons/addon-portainer#15]
# Problem/Motivation

Portainer does not start, same exact error as before: #3 #4 #5. #4 claims to be working and is closed, but that is not the case.

```
-----------------------------------------------------------
 Hass.io Add-on: Portainer v0.4.2
 Manage your Docker environment with ease
 From: Community Hass.io Add-ons
 By: Franck Nijhof <frenck@addons.community>
-----------------------------------------------------------
 amd64 / HassOS 1.13 / HA 0.90.2 / SU 150 / stable
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 
INFO: You are running the latest version of this add-on
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
FATAL: The configured certfile is not found
[cont-init.d] 10-requirements.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.
 
 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
```

## Expected behavior

portainer should be able to start and run

## Actual behavior

fails to start, errors in log

## Steps to reproduce

- Install portainer
- click start
- observe logs

**Comment by frenck** [comment]
@dogmatic69 Please provide FULL logs... this is just telling something is wrong... that is not nice, but without providing actual logs, well, there is not much I can do...

**Comment by frenck** [comment]
Please update portainer to the latest version, it will provide more details on your issue.

**Comment by dogmatic69** [comment]
I've had a look at the debug logs and noticed it was ssl. Seem that is enabled by default regardless of having pem files.
