### ISSUE TITLE
 addon-portainer limited functionality

### ISSUE THREAD

**Issue by Mike-Can** [hassio-addons/addon-portainer#152]
# Problem/Motivation
Running  Debian 11 server with docker  and over  50 containers.  Most containers are not HA related.
Had previously installed the add-on, but I was unable to remotely access and manage the add-on remotely at port 8000, as it only works ingress and under a functional  home assistant instance.
Until now,  I opted to run a standalone portainer  container which worked well for me.
Now, I can’t upgrade home assistant, due to the fact that I must remove the working portainer installation, over the less desirable portainer add-on.
## Expected behavior
1.	Have remote access to portainer without logging into a home assistant instance and then logging into the portainer add-      on.
2.	Have access and manage docker containers via portainer,  by allowing the user make to best choices in managing  their system  without a penalty.
3.	Have portainer add-on container accessible to a desirable port, if the HA instance is offline, or broken.
## Actual behavior
Home Assistant Supervised installation:  “unsupported installation” message after updating,
Home Assistant  log:  “found unsupported images: { ‘tecnativa/docker-socket-proxy’,  ‘portainer/portainer’}  (more-info…..)
Portaineradd-on works, but limited functionality. Only accessible on ingress when HA is running. No web UI or response on port 8000.
Conflict: User must load the home assistant instance to use the portainer for its intended purposes, otherwise no HA updates are made available
## Proposed changes
Whitelist containers which limits or influence functionality of other containers for global use.
Make the portainer add-on fully functional as intended, without routing its functionality via HA.

**Comment by frenck** [comment]
> Running Debian 11 server with docker and over 50 containers. Most containers are not HA related.

That is not a supported setup by Home Assistant.

The portainer add-on is originally created for debugging purposes, for which its current functionality is correct.

Running additional containers on a Home Assistant OS or Supervised system is not supported by the Home Assistant project.

**Comment by Mike-Can** [comment]
Thanks Franck for your quick response!
I am at a loss here, as I don't understand the outcome of my HA problems.

I agree, and perhaps I was directed to wrong place to address it.

In order to mitigate the supervisors upadate limitations, it was suggested that the portainer original image installed in docker is being replaced by your add-on. The containers in question did not run on a home assistant OS. Rather, they run in docker coexisting with the HA container.

If you know, how does one addresses  this conflict?
How do I get an HA update and be able to use portainer coexisting with HA?

**Comment by frenck** [comment]
> Rather, they run in docker coexisting with the HA container.

That is not supported.

> How do I get an HA update and be able to use portainer coexisting with HA?

Run the Home Assistant Container installation type instead.
