### ISSUE TITLE
How to update Portainer?

### ISSUE THREAD

**Issue by jamesngob** [hassio-addons/addon-portainer#153]
# Problem/Motivation

There are newer version of portainer. as of now, it is 2.9.2
Your add-on is 2.0.0

## Expected behavior

I would like to update the Portainer inside HomeAssistant.

## Actual behavior

I click "Auto update" slider but it does not seem to automatically update Portainer

## Proposed changes

Is it possible for users to be able to update the Portainer within HomeAssistant without borthering you? I know you maintain the this Portainer Add-on and you must update it first, then we can update...
But thank you again for your contribution to the community

**Comment by frenck** [comment]
Add-on version doesn't match the portainer version...

Anyhows, this is a feature request, not a bug report.
