### ISSUE TITLE
PANIC: unprotected error in call to Lua API

### ISSUE THREAD

**Issue by fabiangl** [hassio-addons/addon-portainer#16]
# Problem/Motivation
Portainer won't start
> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

[21:32:51] INFO: Starting Portainer...
2019/04/15 21:32:51 Starting Portainer 1.20.2 on 127.0.0.1:9000
[21:32:52] INFO: Starting NGinx...
PANIC: unprotected error in call to Lua API (bad light userdata pointer)
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by malinduta** [comment]
Same issue here.

**Comment by frenck** [comment]
This issue has been solved in the latest release of the addon.
Thanks for reporting this! 👍
