### ISSUE TITLE
Feature Request: Dashboard as entry point

### ISSUE THREAD

**Issue by noxhirsch** [hassio-addons/addon-portainer#17]
# Problem/Motivation

When I used Portainer with the standard docker image, it opened the dashboard first. With the Portainer Hass.io addon it starts with "home". So I have to select the primary endpoint first.

## Proposed changes

I don't know if it's possible to go to the primary dashboard instantly, but it would be more convenient for most of the users (I think most hass.io users only have one endpoint).

Regards,
Nico

**Comment by frenck** [comment]
A user can create/delete their own endpoint, thus changing IDs of the endpoints in the URL. There is no way for me to guarantee this will keep working (once I've set it).

**Comment by noxhirsch** [comment]
What about an optional config like "default_endpoint":"primary"?

**Comment by frenck** [comment]
I've looked at it again today. I really don't see a nice way to solve this without being "hacky".
I've decided to keep it the way it is.

Nevertheless, thank you for your suggestion! ❤️
