### ISSUE TITLE
Allow people to use without Ingress?

### ISSUE THREAD

**Issue by niai** [hassio-addons/addon-portainer#18]
Could you allow this add-on to work without ingress? It's a grate thing but for something like Portainer it would be nice to have direct access back.

**Comment by frenck** [comment]
It already has this, just set a port number in the "Network" section of the add-on configuration.

**Comment by niai** [comment]
I had the port in there but couldn't access it via the port after the update and when I clicked on the port number to try changing it, it changed to "Container  Host  Description" and the text input has gone.

**Comment by frenck** [comment]
That makes no sense to me at all.
Could you provide screenshots? thanks.

**Comment by niai** [comment]
![Screenshot from 2019-04-20 14-42-56](https://user-images.githubusercontent.com/289033/56458130-ad875c00-637a-11e9-90ec-396e424c3402.png)

**Comment by niai** [comment]
Reinstalling fixed it btw.
