### ISSUE TITLE
No containers

### ISSUE THREAD

**Issue by jasonehines** [hassio-addons/addon-portainer#2]
# Problem/Motivation
On the "Home" page I can see containers
![screenshot from 2018-09-16 16 45 49](https://user-images.githubusercontent.com/870809/45600803-b244f580-b9d0-11e8-903b-7ce6f877f745.png) But clicking on them takes me to the primary dashboard where there are no containers listed.

## Expected behavior
I expected a list of containers.

## Actual behavior
No containers listed
![screenshot from 2018-09-16 16 46 56](https://user-images.githubusercontent.com/870809/45600815-f0dab000-b9d0-11e8-9c33-4d385bfcf800.png)

## Steps to reproduce
I installed it and using the default configuration.

**Comment by tjorim** [comment]
Please read [the documentation (README)](https://github.com/hassio-addons/addon-portainer/blob/master/README.md#option-hide_hassio_containers)

> ## Option: hide_hassio_containers
> By default all Hassio managed containers are hidden from Portainer. This is recommended since fooling around with Hassio managed containers can easily lead to a broken system.
> 
> Set this option to false, to gain access to Hassio managed containers as well.

**Comment by jasonehines** [comment]
I've set the option to false and restarted the service, but the result is the same.

**Comment by frenck** [comment]
@jasonehines I should extend the description of that thing.
There are actually 2 things that you need to do.
1) Set the option (which you have done) and restart the add-on.
2) Go into Portainer ->  Settings -> Hidden containers: Delete the listed hidden labels (io.hass.type labels).

**Comment by jasonehines** [comment]
That did it. Thanks

**Comment by frenck** [comment]
Good to hear!

I'm re-opening the issue. Just as a reminder to update the docs. I hope you don't mind.

**Comment by frenck** [comment]
please bot, leave open. I need to pick this up as soon as this add-on can be re-introduced.

**Comment by smartie91** [comment]
i think the hassio addon docs still needs updating as this has taken a lot to find the answer 
thanks

**Comment by frenck** [comment]
That is complaining without a suggestion @smartie91

**Comment by smartie91** [comment]
On the hassio add On page.when you install portainer

**Comment by frenck** [comment]
That is just a simple description page? I already put more info there than normal.

**Comment by frenck** [comment]
Docs are updated, closing this issue.
