### ISSUE TITLE
Remote endpoint port

### ISSUE THREAD

**Issue by supersonical** [hassio-addons/addon-portainer#22]
# Problem/Motivation
Would be a great feature if you could add more endpoints, i have several docker instanses. 

## Proposed changes
Add option to add more ports like port 2375

**Comment by frenck** [comment]
![2019-08-27 18 07 25](https://user-images.githubusercontent.com/195327/63788314-8f67d480-c8f5-11e9-9b83-d5f2c0bafa5b.gif)
