### ISSUE TITLE
Enhancement: Add port mapping 8000 option

### ISSUE THREAD

**Issue by kphonik** [hassio-addons/addon-portainer#24]
# Problem/Motivation

> To manage edge agent endpoints portainer must export port 8000

## Expected behavior

> An option to map ports 80/9000 _and_ 8000

## Actual behavior

> Only possible to map 1 port

## Steps to reproduce

> Configure an "Edge agent" in portainer endpoints where you will see the message "The agent will communicate with Portainer via https://192.168.69.1:9000 and tcp://192.168.69.1:8000"

## Proposed changes

> Create an additive port mapping option with default behavior not exposing the port

**Comment by sinclairpaul** [comment]
In the config.json:

`  "ports": {
    "80/tcp": null,
    "8000/tcp": null
  }, `

Will wait for the PR :)

**Comment by kphonik** [comment]
I figured that was all but wanted to rtfm the addon docs first :-)

**Comment by kphonik** [comment]
@sinclairpaul Any problems with https://github.com/hassio-addons/addon-portainer/pull/25 ?

**Comment by sinclairpaul** [comment]
Not that I see, but you would need @frenck to take a look.
