### ISSUE TITLE
Pulling large images not working via Ingress

### ISSUE THREAD

**Issue by stefangries** [hassio-addons/addon-portainer#26]
# Problem/Motivation

It is not possible to pull larger images like "homegear/rpi-homegear:latest".

## Expected behavior

The image should be pulled.

## Actual behavior

I get an error that the image does not exist. This error only occurs when working via hassio Ingress. The function is working correctly when directly accessing your portainer instance via a defined port.

## Steps to reproduce

1) Go to "Images" in the left hand menu in portainer.
2) Enter "homegear/rpi-homegear:latest" intro the image field.
3) Click "Pull the image".

## Proposed changes

Pulling larger images should work via Ingress as well.

**Comment by frenck** [comment]
I've looked into this, first of all, I'm unable to reproduce this.

However, with this add-on, direct access vs ingress are exactly the same from the add-on side of things. So the only thing I can come up with, it an issue in the Ingress handling inside Home Assistant.

**Comment by stefangries** [comment]
Still having the same problem. In the log on the supervisor page, I always get an "proxy error: context canceled" error, when the download of an image failed. I recently tried it with "homegear/rpi-homegear:nightly". As it is no longer possible to access portainer via a defined port, there is no workaround for me left.

**Comment by sinclairpaul** [comment]
@stefangries As a workaround you could use the SSH/Web Terminal addon, with protection mode disabled.
