### ISSUE TITLE
Client version too new api level 139 vs 140

### ISSUE THREAD

**Issue by mouth4war** [hassio-addons/addon-portainer#27]
# Problem/Motivation

> Cannot pull or import an image oznu/homebridge

## Expected behavior

> Successful import of tar file or image pull

## Actual behavior

> Error message and no image found

## Steps to reproduce

> Attempt to pull the image

## Proposed changes

> Fix api version mismatch

**Comment by mouth4war** [comment]
![Screenshot_20191211-145719](https://user-images.githubusercontent.com/30283635/70608722-9a394180-1c26-11ea-9e0e-9e155f9a4ffb.jpg)

**Comment by mouth4war** [comment]
Tried using 1.39 for DOCKER_API_VERSION and DOCKER_COMPOSE_VERSION in the imported image tar file but still getting the error.

**Comment by ccalica** [comment]
Having this problem as well.

**Comment by mistaecko** [comment]
The Portainer team is [aware of the problem](https://github.com/portainer/portainer/issues/3457#issuecomment-576406143), and will lower the required docker version in the next release.
The immediate fix for HomeAssistant users is to upgrade docker on the host system if possible. This is, however, *not* an option for HassOS users AFAIK.
Hassio users who have upgraded the Portainer addon from an older version, can restore that version from a snapshot (if available). 
For Hassio users with a fresh install of the Portainer AddOn, there is currently no way of installing the previous AddOn version AFAIK.

**Comment by frenck** [comment]
This is addressed in the current dev version of the add-on and will be published on the next release.
