### ISSUE TITLE
Container stats error "invalid option"

### ISSUE THREAD

**Issue by roybosch** [hassio-addons/addon-portainer#29]
# Problem/Motivation

> Container stats won't load

## Expected behavior

> I'd expect to see graphs and other stats

## Actual behavior

> It's giving me the following error: **ps: ps: invalid option -- 'e'**
![image](https://user-images.githubusercontent.com/45666392/72448751-d9275d80-37b7-11ea-9553-0c5cf7a48fc6.png)

## Steps to reproduce

> By clicking on one of these buttons:
![image](https://user-images.githubusercontent.com/45666392/72448649-a715fb80-37b7-11ea-8f2b-7684eefb2469.png)

or:

![image](https://user-images.githubusercontent.com/45666392/72448686-b85f0800-37b7-11ea-8c1e-43ba79aa0962.png)

I'm running Hass.io on a Virtualbox VM on an Intel NUC.

## Proposed changes

> I found this topic: https://github.com/hassio-addons/addon-portainer/issues/3. Seems there was a fix before.

**Comment by frenck** [comment]
Tested on different platforms, works for me

![image](https://user-images.githubusercontent.com/195327/75287988-b3ac5b80-581b-11ea-89dd-96bd4bc687f6.png)


This might be related to your system.

**Comment by roybosch** [comment]
@frenck So you didn't change anything? Now it does work for me too. No more error messages.
