### ISSUE TITLE
Feature Request: Adding the AGENT_SECRET environment variable inside of the config

### ISSUE THREAD

**Issue by jacoknapp** [hassio-addons/addon-portainer#30]
# Problem/Motivation

Currently there isn't a good way to add the AGENT_SECRET inside of the portainer config. This Env Var allows you to be able to connect to remote portainer agents on external docker servers, only if the portainer agent also has the same shared secret. 

This secret only takes affect when one the agent is restarted, because the agent utilized a trust first connection approach. This is bad if a malicious actor manages to connect to the agent first. To combat this they added the shared AGENT_SECRET env var, which will cause the agent to only pair with the first connection that has the shared secret as well.

As always thank you for all of your great work!

**Comment by frenck** [comment]
Merged in dev, will be part of the next release
