### ISSUE TITLE
Can't see containers

### ISSUE THREAD

**Issue by malogic** [hassio-addons/addon-portainer#35]
# Problem/Motivation

When i open Portainer in have one Primary Endpoint. in the description it say that i have 15 (12 active) containers. (that sounds accurate)
When i open the endpoint dashboard i can only see two containers and they are both inactive.

## Expected behavior

To be able to see and manage all containers that is installed via Homeassistant

## Actual behavior

I can only see the 17 images and two inactive containers and 4 networks. no stacks or volumes vissible.

## Steps to reproduce

Don't know if possible

## Proposed changes

None

###
Log
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Hass.io Add-on: Portainer
 Manage your Docker environment with ease
-----------------------------------------------------------
 Add-on version: 0.9.0
 You are running the latest version of this add-on.
 System: Ubuntu 18.04.3 LTS  (amd64 / qemux86-64)
 Home Assistant version: 0.105.5
 Supervisor version: 201
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] portainer.sh: executing... 
[cont-init.d] portainer.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[15:12:38] INFO: Starting Portainer...
[services.d] done.
2020/02/25 15:12:39 Templates already registered inside the database. Skipping template import.
2020/02/25 15:12:39 Instance already has defined endpoints. Skipping the endpoint defined via CLI.
2020/02/25 15:12:39 server: Reverse tunnelling enabled
2020/02/25 15:12:39 server: Fingerprint XXXXXXXXXXXXXXXXXXXXXXX
2020/02/25 15:12:39 server: Listening on 0.0.0.0:8000...
2020/02/25 15:12:39 Starting Portainer 1.23.0 on 127.0.0.1:9000
2020/02/25 15:12:39 [DEBUG] [chisel, monitoring] [check_interval_seconds: 10.000000] [message: starting tunnel management process]
[15:12:39] INFO: Starting NGinx...
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)

**Comment by frenck** [comment]
Try the manual: <https://github.com/hassio-addons/addon-portainer#known-issues-and-limitations>
