### ISSUE TITLE
Can't update Portainer via HA Add-ons page

### ISSUE THREAD

**Issue by SVhuMMer** [hassio-addons/addon-portainer#38]
# Problem/Motivation

The hass.io add-ons tab shows Portainer update is available from 1.0.0 to 1.1.0, however, the system cannot fetch the image. 

## Expected behavior

Package gets updated to 1.1.0

## Actual behavior

Package does not get updated, the log shows the following errors:
20-04-01 14:21:37 INFO (SyncWorker_10) [supervisor.docker.interface] Update image hassioaddons/portainer-amd64:1.0.0 to hassioaddons/portainer-amd64:1.1.0
20-04-01 14:21:37 INFO (SyncWorker_10) [supervisor.docker.interface] Pull image hassioaddons/portainer-amd64 tag 1.1.0.
20-04-01 14:21:53 ERROR (SyncWorker_10) [supervisor.docker.interface] Can't install hassioaddons/portainer-amd64:1.1.0 -> 404 Client Error: Not Found ("no such image: hassioaddons/portainer-amd64:1.1.0: No such image: hassioaddons/portainer-amd64:1.1.0").
20-04-01 14:21:59 INFO (SyncWorker_18) [supervisor.docker.interface] Update image hassioaddons/portainer-amd64:1.0.0 to hassioaddons/portainer-amd64:1.1.0
20-04-01 14:21:59 INFO (SyncWorker_18) [supervisor.docker.interface] Pull image hassioaddons/portainer-amd64 tag 1.1.0.
20-04-01 14:22:16 ERROR (SyncWorker_18) [supervisor.docker.interface] Can't install hassioaddons/portainer-amd64:1.1.0 -> 404 Client Error: Not Found ("no such image: hassioaddons/portainer-amd64:1.1.0: No such image: hassioaddons/portainer-amd64:1.1.0").

## Steps to reproduce

Click on "Update" button on hass.io Add-ons tab in Supervisor section
## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
404 usually means there is not enough disk space left to complete the download, install and update procedure.

From the add-on end, there is nothing I can do, as this part of the error is outside of the control of an add-on.

**Comment by SVhuMMer** [comment]
Dear frenck, thank you for a prompt reply. I doubt disk space is an issue here, as all other updates (or any other actions for that matter) occur with no problem, and ubuntu shows 2% disk usage. Docker containers are also fine, 11% usage. Still, the issue persists: I can't update Portainer via HASS.IO interface. It may not be at the add-on end, but do you have any other ideas what I can do/check to identify the problem?

**Comment by frenck** [comment]
The image exists: <https://hub.docker.com/layers/hassioaddons/portainer-amd64/1.1.0/images/sha256-24a7f4702d7da77b9f29a06f44e50552ea44533293c71624e9d60bab9d11735c?context=explore>

I've seen more issue with Dockerhub lately, which seems to be location-based issues. However, from my end, there is nothing I can do about it.

**Comment by SVhuMMer** [comment]
Problem solved! 

It turned out this error occurs if the user tries to update the Portainer addon with Protection Mode enabled in HASS.IO supervisor menu. Once Protection Mode is turned off, the module gets updated normally.

Maybe this is very obvious, and it's my lack of knowledge about the Protection Mode, or maybe it could be mentioned somewhere in the update instructions.
