### ISSUE TITLE
Re-add the ability to set a custom port in the netwerksettings

### ISSUE THREAD

**Issue by svh1985** [hassio-addons/addon-portainer#39]
# Problem/Motivation

On multiple occasions I was able to debug and fix Home Assistant docker issues with Portainer. Of course I could have used docker cli, but Portainer is very powerfull and just easier 😄
Why can't Ingress and the direct access support coexist? I understand this would be fine for some add-ons, but Portainer is just too important for debugging. Because now, if Hass is down, Portainer is unreachable.

## Proposed changes

Can you please (re)add the ability to map a custom port (like 9000) to Portainer?

Thanks 😄

**Comment by frenck** [comment]
That won't be re-added.

**Comment by svh1985** [comment]
Ok, clear. Don't get me wrong, I love what you do for HA and I use your add-ons every day. But I'm curious know why it's removed? There might be a good explanation, but the release notes didn't mention the motivation. Removing functionality is always bad for the user, unless there is of course a good reason for it 😄 

Thanks! 🙌

**Comment by frenck** [comment]
Maintaining both entry points require a lot of additional logic to maintain and is more error-prone in general. (e.g., an additional reverse proxy is needed to make it work).

With recent changes and additions to Home Assistant, a system should always be able to start and the user will be able to access add-ons.
