### ISSUE TITLE
Portainer failing to start

### ISSUE THREAD

**Issue by pauly7300** [hassio-addons/addon-portainer#4]
# Problem/Motivation

Installation seems to work fine.  When starting portainer after adding some additional config info, the add-on won't start successfully.  
Note: I have used the 'leave_front_door_open' option.  Here is my config:
`{
  "log_level": "debug",
  "ssl": false,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "hide_hassio_containers": false,
  "leave_front_door_open": true
}`

## Expected behavior

Would expect it to start based on the documentation and steps followed.

## Actual behavior

addon doesn't start and gives general 'oops' message.  Rerunning with debug logging on I see the following.  https://pastebin.com/K2aG6QN2

## Steps to reproduce

I'm running hassio version 79.3 and installed the latest version of the portainer add-on 0.2.0.

## Proposed changes

NA

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/K2aG6QN2">{    "log_level": "debug",    "ssl": false,    "certfile": "fullchain.pem",    " - Pastebin.com</a></strong></div></blockquote>

**Comment by lettore** [comment]
I have a similar issue with a totally new image of Hassos 1.11 and supervisor 133.

**Comment by tjorim** [comment]
Due to recent changes to Hass.io (the supervisor), there is currently no way to give add-ons like SSH and this Portainer add-on the necessary rights to docker.
In the future you will be able to do this via the UI but at the moment it's not implemented (in HA, not specific to this add-on).

**Comment by snelweg** [comment]
So this is useless right now, is that what you are saying?

**Comment by frenck** [comment]
This can actually be closed.
The add-on is working and available again.
