### ISSUE TITLE
Describe functionality and purpose

### ISSUE THREAD

**Issue by richardsj** [hassio-addons/addon-portainer#41]
# Problem/Motivation

The Github page does not make it clear what this add-on does and when you would need it

## Expected behavior

Before installing it's not clear what the interaction between Portainer and HomeAssistant is, or what the goal/benefit is

## Proposed changes

Describe what order to install these components in (e.g. Portainer first, then Hass in docker, then add-on, in order to ........?)

**Comment by frenck** [comment]
There is no order. If you don't know what Portainer is for, you should not use it in the first place.
