### ISSUE TITLE
Enhancement: Add mapping for port 9000

### ISSUE THREAD

**Issue by JoostvdB94** [hassio-addons/addon-portainer#44]
# Problem/Motivation

When setting up portainer to work with edge agents, I came across the issue that the HTTP port for portainer is not exposed.
Unless I can supply authentication for homeassistant via the portainer agent (which I think is impossible) I need this port mapping alongside the ingress implementation.

## Expected behavior

The ability to specify the HTTP port in the addon screen

## Actual behavior

Only port 8000 can be specified

## Steps to reproduce

Open addon settings

## Proposed changes
Please add the mapping for port 9000 again to make use of edge agents.

**Comment by frenck** [comment]
Port 9000 is for Portainer itself, not the agent API. This add-on will not expose its interface directly alongside ingress. This change has been made quite some time ago.

**Comment by JoostvdB94** [comment]
I'm aware that port 8000 is used for the Agent API, not 9000. However, an edge agent needs both 9000 and 8000 as described in this article https://www.portainer.io/2019/07/how-does-the-edge-agent-work/

Without the possibility to expose port 9000, i cannot find a way to reach the Portainer API. Maybe there is a way to utilize the ingress endpoint from HomeAssistant?
