### ISSUE TITLE
error-unable-to-retrieve-stack-list

### ISSUE THREAD

**Issue by Tao173** [hassio-addons/addon-portainer#45]
I use an armbian system Under the docker environment, after I install portainer, I cannot view the stack, just like #32, but when I use ubuntu, everything is normal. homeassistant is the latest version, all are docker.

**Comment by frenck** [comment]
Both mentioned systems are not supported by Home Assistant.

**Comment by shawnli87** [comment]
I am having this issue on Home Assistant Operating System

**Comment by shellux** [comment]
Same here with home assistant supervised on a intel nuc

**Comment by Tao173** [comment]
> Operating System



> 我在家庭助理操作系统上遇到此问题
> 
> ```
> 2020/10/06 23:02:57 http error: Invalid query parameter: filters (err=invalid character '%' looking for beginning of value) (code=400)
> 2020/10/06 23:06:39 http error: Invalid query parameter: filters (err=invalid character '%' looking for beginning of value) (code=400)
> 2020/10/06 23:07:35 http error: Invalid query parameter: filters (err=invalid character '%' looking for beginning of value) (code=400)
> 2020/10/06 23:08:23 http error: Invalid query parameter: filters (err=invalid character '%' looking for beginning of value) (code=400)
> ```

Operating System???  Is it an official customized system? If so, I think the official will solve it

**Comment by shawnli87** [comment]
> > Operating System
> 
> > 我在家庭助理操作系统上遇到此问题
> > ```
> > 2020/10/06 23:02:57 http error: Invalid query parameter: filters (err=invalid character '%' looking for beginning of value) (code=400)
> > 2020/10/06 23:06:39 http error: Invalid query parameter: filters (err=invalid character '%' looking for beginning of value) (code=400)
> > 2020/10/06 23:07:35 http error: Invalid query parameter: filters (err=invalid character '%' looking for beginning of value) (code=400)
> > 2020/10/06 23:08:23 http error: Invalid query parameter: filters (err=invalid character '%' looking for beginning of value) (code=400)
> > ```
> 
> Operating System??? Is it an official customized system? If so, I think the official will solve it

Home Assistant Operating System (formerly HassOS). It's the recommended installation.
