### ISSUE TITLE
Can't install container

### ISSUE THREAD

**Issue by asalexsu** [hassio-addons/addon-portainer#47]
# Problem/Motivation

> I was trying to install deepstack AI for blue iris integration on HASSIO

## Expected behavior

> container to be downloaded the deployed

## Actual behavior

> Error on Portainer, works in actual command line using docker pull

## Steps to reproduce

> same as 
https://community.home-assistant.io/t/portainer-issue-with-creation-of-new-container/194757/20

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
#26 

I doubt there is anything that can be done from an addon perspective.
