### ISSUE TITLE
Cannot pull any image.

### ISSUE THREAD

**Issue by famewolf** [hassio-addons/addon-portainer#52]
# Problem/Motivation
I am attempting to install homebridge in a docker container.  I also tried installing lighttpd.  Both give a red "Failed to pull image" when trying to download them.

## Steps to reproduce

> (How can someone else make/see it happen)

On a clean install of the home assistant image install the portainer addon, disable protected mode as instructed and start the container.  Access the webui and try to pull any image but specifically lighttpd and homebridge.   Why do I want homebridge when home assistant has homekit?   I have added all my broadlink rm pro devices AND my switchmate bluetooth devices to homebridge and they work great.   I saw no EASY method to integrate them into home assistant and it makes no sense to run two pi's just so homebridge and home assistant can run on the same lan.

Thank you for your time.

![Screenshot_20201122_000940](https://user-images.githubusercontent.com/4558832/99915440-a2707c80-2cd1-11eb-9dfe-6b771f58b8d2.png)

**Comment by frenck** [comment]
Anything in the logs?

**Comment by deftdawg** [comment]
@famewolf my luck has been hit and miss with pulling images...   I'm on arm64/HassOS, while I see you're on armv7 (Pi3?)...  I'm not sure if that's armhf or if the armv6 in latest images in [onzu/homebridge](https://hub.docker.com/r/oznu/homebridge/tags) would work on arm7, you might try a different tag that has v7.

For me I've managed to successfully pull:
- hello-world
- openjdk (470 MB)

You might try some of those... 

I've tried some arm64 builds of keycloak [ jboss/keycloak doesn't have arm64 ], but neither pulls for me:
- [alemairebe/keycloak:11.0.3](https://hub.docker.com/r/alemairebe/keycloak/tags) --> ``2020/11/23 02:31:14 proxy error: context canceled`` is what shows up in the log
- [cyrilix/keycloak](https://hub.docker.com/r/cyrilix/keycloak/tags) --> ``2020/11/23 02:38:19 proxy error: context canceled``

Both of these spend like what feels like 10 minutes with the "Download in progress... " before timing out with "Failure to pull image" like the screenshot.   Both images are smaller than 470MB (size of openjdk that downloaded ok), and host has 12GB free, so not sure why they'd fail like that.

**Comment by famewolf** [comment]
First,  thank you so much for replying! I get similar behavior where it downloads a while before timeing out...in fact if I try to pull it multiple times I'll eventually get an error indicated I've reached my "rate limit" and need to login to download more....of course no method to log into dockerhub is visible.   The raspberry pi 3b I am using is armhf (which is a new one on me as I only knew about armv6,v7 and v8.  armv7 code seems to run fine on it.   I'll try the hello-world tomorrow.   I was pulling oznu/homebridge with the "raspberrypi3" tag or that's what the instructions said to point to when building the container but I never got that far.  Not sure what other "version" I should try.  I tried another user's version of homebridge that was also on dockerhub and again identical behavior.

@frenck I didn't see anything but I could have missed it.  I'll recheck when I try to pull hello world.  Thanks for the followup!

**Comment by deftdawg** [comment]
@famewolf for the rate limit stuff, if you need to put in your dockerhub login, under the repositories section of portainer theres an authentication toggle switch you can flip to use your login credentials with.

**Comment by frenck** [comment]
it can be caused by Ingress itself as well. To circumvent that, assign a port to the Portainer add-on in the add-on network settings and access it that route.

**Comment by sinclairpaul** [comment]
> To circumvent that, assign a port to the Portainer add-on in the add-on network settings and access it that route.

Didn't direct access get removed? 😉 

You could however use the Community SSH addon and attempt to pull the images using that to rule out any ingress issues.

**Comment by frenck** [comment]
Nope...

https://github.com/hassio-addons/addon-portainer/blob/master/portainer/config.json#L16-L21

**Comment by deftdawg** [comment]
ingress proxy timing out makes sense to me as a possible cause.

> Nope...
> 
> https://github.com/hassio-addons/addon-portainer/blob/master/portainer/config.json#L16-L21

Hitting port 8000 after enabling it in the add-on networking returns "Not Found", so don't think that port offers a way for a user to control portainer, perhaps @sinclairpaul was referring to this commit from Feb?

https://github.com/hassio-addons/addon-portainer/commit/f183932d6014bad02d0c8ba7c7d4694c46ae47f8#diff-b4e82acc44ac25b17828f0821436e22c3b204b6bf3a57b5f26d119d6d9b5b7ec

**Comment by frenck** [comment]
No @sinclairpaul was right, you can work without ingress on this add-on.

**Comment by famewolf** [comment]
Ok first....when I use the ssh addon (there are two but they seem to work same way) it's putting me inside the docker container ie "docker" results in a command not found error.  
2nd this may be relevant:
On November 20, 2020, rate limits anonymous and free authenticated use of Docker Hub went into effect. Anonymous and Free Docker Hub users are limited to 100 and 200 container image pull requests per six hours.

If this proxy is being used by everyone then that could easily be getting hit.  Using my credentials is not going to help as their only solution is "To increase your pull rate limits you can upgrade your account to a Docker Pro or Team subscription."

**Comment by famewolf** [comment]
Also I mapped port 8000 and restarted the addon....get 404 trying to connect to it from another pc on the lan but the webui loads so not sure where to go with it now.

**Comment by sinclairpaul** [comment]
@famewolf Docker rate limits are primarily based on source address, you can see more at https://docs.docker.com/docker-hub/download-rate-limit/.  If you are running something such as watchtower, I would suggest you remove it.

You cannot access the Portainer addon outside of ingress.

**Comment by famewolf** [comment]
@sinclairpaul hmm I'm glad you said something....my pi isn't running it but my freenas server has watchtower.  Guess I'll have to stop it and run it manually now and again.  I'm on a wifi hotspot...I should be able to cycle the connection and get a new ip which is what I did with previous rate limit errors but was still unable to pull an image.
