### ISSUE TITLE
Motioneye Container - standard_init_linux.go:219: exec user process caused: exec format error

### ISSUE THREAD

**Issue by mAsHERbtm** [hassio-addons/addon-portainer#54]
Hi, 

I need run container:  https://hub.docker.com/r/jshridha/motioneye
Container must have parameter: 

```
docker run -d --name=motioneye \
    --device=/dev/video0 \
    -p 8081:8081 \
    -p 8765:8765 \
    -e TIMEZONE="America/New_York" \
    -e PUID="99" \
    -e PGID="100" \
    -v /mnt/user/appdata/motioneye/media:/home/nobody/media \
    -v /mnt/user/appdata/motioneye/config:/config \
    jshridha/motioneye:latest
```

I add only ports and env: TIMEZONE, PUID, PGID but still show  the same error:  
**`standard_init_linux.go:219: exec user process caused: exec format error`**

![obraz](https://user-images.githubusercontent.com/22257343/101874286-e942eb00-3b88-11eb-8a07-de711e772fe7.png)

------------------------------------------------------
**My hardware environment**
```
Raspberry Pi4 4GB
docker --version: 19.03.12
portainer: 1.3.0
Home Assistant 0.118.4
Hass.io: HassOS 4.17
```

Screen1:
![obraz](https://user-images.githubusercontent.com/22257343/101872597-d11d9c80-3b85-11eb-81a5-914c86b33257.png)

Screen2:
![obraz](https://user-images.githubusercontent.com/22257343/101872617-dbd83180-3b85-11eb-9dda-f09921930531.png)

Screen3 - env:
![obraz](https://user-images.githubusercontent.com/22257343/101872641-e397d600-3b85-11eb-87de-ba2bfe918c2c.png)

-----------------------------------------------------
maybe I miss some options in: "Command & logging"  or "Volumes" ??

**--# NOTE1:** 
I noticed that after deploying container it creates "Host / volume" in:
```

-  /config
- /home/nobody/motioneye
```
![obraz](https://user-images.githubusercontent.com/22257343/101872882-4a1cf400-3b86-11eb-8c96-556abca47b60.png)

but I dont have directory "nobody".
config is ok

![obraz](https://user-images.githubusercontent.com/22257343/101873442-3920b280-3b87-11eb-82fc-02b803680358.png)

**--# NOTE2:** 
After deploying container i see in Container details: 

`CMD: /sbin/my_init` 

Is this really correct?

![obraz](https://user-images.githubusercontent.com/22257343/101873069-97996100-3b86-11eb-81dd-99b38d789e6d.png)

I need help :(

**Comment by Kipjr** [comment]
> exec user process caused: exec format error

This often means that you have the wrong architecture . amd64 application on ARMv7 Raspberry Pi architecture

**Comment by frenck** [comment]
This indeed means you are mixing up architectures. This is not an add-on problem/issues but a user error.
