### ISSUE TITLE
portainer not listed as an addon in the community repository

### ISSUE THREAD

**Issue by kiwijunglist** [hassio-addons/addon-portainer#6]
See this page:
https://github.com/hassio-addons/repository

There is no portainer it is missing.

<blockquote><img src="https://avatars1.githubusercontent.com/u/30772201?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/hassio-addons/repository">hassio-addons/repository</a></strong></div><div>Community Hass.io Add-ons for Home Assistant. Contribute to hassio-addons/repository development by creating an account on GitHub.</div></blockquote>

**Comment by frenck** [comment]
Correct.
The add-on cannot work at this moment and has therefore been removed temporarily from the add-on store.

We are awaiting a UI update for Hass.io in order for this add-on to be available again.
