### ISSUE TITLE
Cant see any Container in Portainer on Hassos 5.10

### ISSUE THREAD

**Issue by rubkec** [hassio-addons/addon-portainer#64]
when is login to portainer i can see 15 containers running on the homepage

![image](https://user-images.githubusercontent.com/56980377/105838548-84284500-5fd0-11eb-912b-d3c24be6d134.png)

but when i go to containers, there are no containers visible
![image](https://user-images.githubusercontent.com/56980377/105838631-a0c47d00-5fd0-11eb-82f8-82b9554f68a4.png)

**Comment by ludeeus** [comment]
This is because you should not mess with the containers managed by the Supervisor.
<https://github.com/hassio-addons/addon-portainer/blob/main/portainer/DOCS.md#known-issues-and-limitations>

**Comment by rubkec** [comment]
ok, my bad, you can close the issue

is it just a label in portainer? for those hidden containers? wil it break the hassos configuration?
