### ISSUE TITLE
Portainer addon starts but dies immediatly when visiting the portainer page

### ISSUE THREAD

**Issue by simgunz** [hassio-addons/addon-portainer#75]
# Problem/Motivation

Just installed HassOS 5.11 on a Raspberry Pi 4. Installed the Portainer addon, I can start it but as soon as I visit the Portainer page the addon dies and I am asked to start it again.

## Expected behavior

Portainer addon starts

## Actual behavior

Portainer addon does not start

## Steps to reproduce

1. Start portainer addon
2. Navigate to the Portainer menu item in the sidebar

## Logs

```
Feb 21 16:56:19 homeassistant hassos-supervisor[881]: 21-02-21 16:56:19 INFO (SyncWorker_3) [supervisor.docker.interface] Cleaning addon_a0d7b954_portainer application
Feb 21 16:56:21 homeassistant hassos-supervisor[881]: 21-02-21 16:56:21 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/portainer/aarch64 with version 1.4.0
```

**Comment by sinclairpaul** [comment]
Can you please post the addon logs

**Comment by simgunz** [comment]
I've now noticed the `Log` tab on the addon page. There is a clear message that says to disable `protection mode` to make the portainer addon work. So my fault, I should have RTFM :-)
