### ISSUE TITLE
Portainer 2.0

### ISSUE THREAD

**Issue by Zehir** [hassio-addons/addon-portainer#76]
Hi,

About this message on #55
> 
> Probably never, this add-on is most likely to be deprecated.
> Portainer chooses a different path of 2.0, which is not a good direction for the add-on.
> 
> _Originally posted by @frenck in https://github.com/hassio-addons/addon-portainer/issues/55#issuecomment-743117749_
> 

Is there any alternative to this addon ?

**Comment by frenck** [comment]
The command line 👍
