### ISSUE TITLE
containers not showing correctly

### ISSUE THREAD

**Issue by GHSTUDIO1** [hassio-addons/addon-portainer#79]
I have installed the latest portainer supervisor addon.  When I open it the home page Primary shows 0 stacks, 16 containers (15 open, 1 not open) and 16 images.  When I then go to the summary page, it says I have 0 containers and 16 images. The containers page is blank.  I am running a number of HA containers...and if I recall, portainer itself should show as a container.

I'm running Home Assistant supervised (core-2021.3.4) in a proxmox (6.3) VM  using the debian 10 LXC and docker.   Portainer 1.24.0

Even though it's a complex install and there are alternatives, the strange part is that clearly, portainer knows there are 16 containers on the home page, but then it doesn't show that they exist when you go further and try to show and/or work with them.

**Comment by frenck** [comment]
> LXC

Is not recommend, and not supported by the Home Assistant project.

**Comment by GHSTUDIO1** [comment]
This issue is not related to LXC.

Home Assistant supervised apparently starts all home assistant docker
containers as hidden.  Portainer lists all the images but they show as
unused (this is a known portainer error for hidden containers...they are in
fact used), the summary shows that containers exist, but when you try to
show the containers, they are hidden.

**Comment by frenck** [comment]
yes and that is documented in the add-on documentation. Yet, you should not run this stuff on LXC.
