### ISSUE TITLE
Portainer integration won't install

### ISSUE THREAD

**Issue by hutchwilco** [hassio-addons/addon-portainer#82]
# Problem/Motivation

> Portainer won't install when "Install" is clicked in HA addon store.

## Expected behavior

> Expect to see "Installing..." and an activity swirly thing, then: Installed.... Start integration.... options

## Actual behavior

>Literally nothing happens - like the Install link/button is dead.

## Steps to reproduce

> Try to install portainer integration from the HA addon store. 
currently running version HA core-2021.3.0 and HASSOS 5.12. Tried a HA restart.

## Proposed changes

>would be great if it could install when I click install.

**Comment by frenck** [comment]
Cannot reproduce. This seems to be something with your system.
Besides, this is an add-on. Installing/managing the add-on is not provided by the add-on itself (as well, it isn't installed even in your case). So there is no amount of code I can adjust to fix that.

Please report your issue with the Home Assistant project. Thanks 👍

**Comment by hutchwilco** [comment]
@frenck thank you. 
For others who might stumble on this, my issue was caused by lack of free drive space. Although the host monitoring stated 2Gb free, and there were no relevant items in the HA log, the HA supervisor log stated errors when updating or attempting to install Portainer due to only 0.7Gb remaining.
