### ISSUE TITLE
Can't embed Portainer as panel

### ISSUE THREAD

**Issue by tjorim** [hassio-addons/addon-portainer#9]
# Problem/Motivation

Due to `X-Frame-Options: deny` in Portainer it's not always possible to embed Portainer as an iframe panel.

## Expected behavior

Users can embed Portainer in Hass.io

## Actual behavior

Users can't

## Steps to reproduce

Use portainer, try to embed it as an iframe panel in Hass.io
This does not work when using Tor or reverse proxy (sometimes)

## Proposed changes

Update Portainer to upstream release 1.20.0 (https://github.com/portainer/portainer/issues/2279)

**Comment by frenck** [comment]
1.20.0 is not yet available as binary distribution, awaiting release of those.

**Comment by frenck** [comment]
@HetorusNL Not sure why that is relevant?
But thanks anyways.

**Comment by frenck** [comment]
@HetorusNL I know how Caddy works... But that is not solving the issue... (it is a very specific workaround). So not sure how to attributes to fixing the issue. (Hence previous response).

**Comment by frenck** [comment]
This is fixed with the current release.
